name: Generate PDF

on:
  push:
    branches:
      - master
    paths:
    - '_pages/**'
    - '_posts/**'
    - '.pandoc/**'
     
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: sudo apt install -y texlive-latex-extra texlive-xetex texlive-lang-german && wget https://github.com/jgm/pandoc/releases/download/2.6/pandoc-2.6-1-amd64.deb && sudo apt install ./pandoc-2.6-1-amd64.deb

      - name: Run pandoc
        run: pandoc -s -f markdown _pages/about.md _posts/* --output=assets/download/acab.pdf --resource-path=assets --pdf-engine=xelatex --template=.pandoc/template.latex --lua-filter=.pandoc/remove-toc.lua -V documentclass=report

      - name: push changes to remote
        run: |
             git config --global user.name "Pandoc Bot"

             git add assets/download/acab.pdf 
             git commit -m "Upload latest .pdf"
             git push
