name: Generate PDF

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run pandoc
        uses: docker://pandoc/core:2.9
        with:
          args: |
            -s -f markdown _pages/about.md _posts/*
            -o acab.pdf
            --resource-path=assets
            --pdf-engine=xelatex
            --template=.pandoc/template.latex 
            --lua-filter=.pandoc/remove-toc.lua
