name: Jekyll site CI

on:
  workflow_dispatch: # run manually
  push:

    branches: 
      - master
    paths-ignore:
      - '.github/**'
      - '.pandoc/**'
      
  pull_request:
    branches: 
      -  master
    paths-ignore:
      - '.github/**'
      - '.pandoc/**'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install -y libjpeg62 libjpeg62-dev
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
