name: Check markdown links
on: push
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Link Checker
      id: lc
      uses: peter-evans/link-checker@v1
      with:
        args: -r _pages _posts -d . -x '^(?:[^h]+|h(?:$|[^t]|t(?:$|[^t])))*$'
    - name: Fail if there were link errors
      run: exit ${{ steps.lc.outputs.exit_code }}
